# This deployment uses the simple viewer app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qgis-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qgis-viewer
  template:
    metadata:
      labels:
        app: qgis-viewer
    spec:
      initContainers:
      - name: init-dirs
        image: alpine:3.18
        command:
        - sh
        - -c
        - |
          echo "Creating directory structure..."
          mkdir -p /usr/share/nginx/html/js
          mkdir -p /usr/share/nginx/html/css
          mkdir -p /favicon
          chmod -R 755 /usr/share/nginx/html
          chmod -R 755 /favicon
          cp -fv /favicon-source/favicon.ico /favicon/
          echo "Directory structure created successfully."
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html
        - name: favicon-volume
          mountPath: /favicon
        - name: favicon-source
          mountPath: /favicon-source
          readOnly: true
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html
        - name: viewer-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: js-content
          mountPath: /usr/share/nginx/html/js/main.js
          subPath: main.js
        - name: css-content
          mountPath: /usr/share/nginx/html/css/main.css
          subPath: main.css
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: favicon-volume
          mountPath: /favicon
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: web-root
        emptyDir: {}
      - name: viewer-html
        configMap:
          name: qgis-viewer-html
          defaultMode: 0644
      - name: js-content
        configMap:
          name: qgis-viewer-js
          defaultMode: 0644
      - name: css-content
        configMap:
          name: qgis-viewer-css
          defaultMode: 0644
      - name: nginx-config
        configMap:
          name: viewer-nginx-config
          defaultMode: 0644
      - name: favicon-source
        configMap:
          name: qgis-favicon
          defaultMode: 0644
      - name: favicon-volume
        emptyDir: {}
