apiVersion: apps/v1
kind: Deployment
metadata:
  name: qgis-viewer
  labels:
    app: qgis-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qgis-viewer
  template:
    metadata:
      labels:
        app: qgis-viewer
    spec:
      containers:
      - name: viewer
        image: brakmic/qgis-viewer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
