apiVersion: v1
kind: Pod
metadata:
  name: data-debug
  namespace: qgis-system
spec:
  containers:
  - name: debug
    image: alpine:3.18
    command: ["sleep", "3600"]
    volumeMounts:
    - name: host-data
      mountPath: /data
  volumes:
  - name: host-data
    hostPath:
      path: /host_workspace/scratchpad/qgis-test/data
      type: Directory
